# -*- coding: utf-8 -*-
"""IT-RouteOptimization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwXSGk6qXFQrOYxNy6-kSwQUnicsQP4k
"""

# PART 1: INSTALL LIBRARIES
!pip install osmnx folium geopy openpyxl
!pip install googlemaps

# PART 2: IMPORT LIBRARIES AND READ DATA
import osmnx as ox
import folium
from geopy.distance import geodesic # Not directly used for main pathfinding anymore, but kept for historical context/potential future use.
import itertools
import pandas as pd
from datetime import datetime, time # Import datetime for parsing departure times

# --- Vehicle Type Definitions ---
# Define default parameters for different vehicle types
vehicle_type_definitions = {
    "car": {"L_PER_100KM": 7, "AVG_SPEED_KMH": 40, "NETWORK_TYPE": "drive", "departure_time": "09:00"},
    "motorcycle": {"L_PER_100KM": 3, "AVG_SPEED_KMH": 30, "NETWORK_TYPE": "drive", "departure_time": "08:30"},
    "truck": {"L_PER_100KM": 15, "AVG_SPEED_KMH": 35, "NETWORK_TYPE": "drive", "departure_time": "07:00"}
}

# Default parameters
DEFAULT_L_PER_100KM = 7  # Liters per 100 kilometers
DEFAULT_AVG_SPEED_KMH = 40  # Average speed in kilometers per hour
COST_PER_LITER = 25000  # VND per liter (example value)

# --- Helper function to get vehicle parameters ---
def get_vehicle_params(vehicle_name):
    params = vehicle_parameters.get(vehicle_name, {})
    vehicle_type = params.get('type', 'car')  # Default to 'car' if not specified

    # Start with default parameters for the determined vehicle type
    final_params = vehicle_type_definitions.get(vehicle_type, vehicle_type_definitions['car']).copy()

    # Override with specific vehicle parameters if provided
    final_params.update(params)

    # Ensure essential parameters are present, using global defaults if necessary
    final_params['L_PER_100KM'] = final_params.get('L_PER_100KM', DEFAULT_L_PER_100KM)
    final_params['AVG_SPEED_KMH'] = final_params.get('AVG_SPEED_KMH', DEFAULT_AVG_SPEED_KMH)
    # Ensure NETWORK_TYPE is also set from vehicle_type_definitions if not explicitly overridden
    final_params['NETWORK_TYPE'] = final_params.get('NETWORK_TYPE', vehicle_type_definitions[vehicle_type]['NETWORK_TYPE'])

    return final_params

# --- Vehicle Assignment Configuration ---
# Example: Assign specific STT values to vehicles
vehicle_parameters = {
    "Vehicle A": {"type": "motorcycle", "departure_time": "01:00"},
    "Vehicle B": {"type": "truck", "L_PER_100KM": 15, "departure_time": "12:30"},
    "Vehicle C": {"type": "car", "AVG_SPEED_KMH": 7, "departure_time": "18:00"}
}

default_vehicle_assignments = {
    "Vehicle A": [1, 2, 19],
    "Vehicle B": [4, 13],
    "Vehicle C": [6, 12]
}

# --- Data Loading and Preprocessing ---
def load_and_process_data(file_path):
    # Read the Excel file
    df = pd.read_excel(file_path)

    # Normalize column names to lowercase for easier access
    df.columns = df.columns.str.lower()

    # Rename 'stt' to 'id' for consistency if it exists
    if 'stt' in df.columns:
        df = df.rename(columns={'stt': 'id'})

    # Identify latitude and longitude columns dynamically or use defaults
    lat_col = 'latitude'
    lon_col = 'longitude'

    # Ensure latitude and longitude are numeric
    df[lat_col] = pd.to_numeric(df[lat_col], errors='coerce')
    df[lon_col] = pd.to_numeric(df[lon_col], errors='coerce')

    # Drop rows with NaN values in latitude or longitude
    df.dropna(subset=[lat_col, lon_col], inplace=True)

    # If 'id' column was not originally 'stt' and doesn't exist, create a simple one
    if 'id' not in df.columns:
        df['id'] = df.index + 1

    return df, lat_col, lon_col

def assign_stops_by_stt_values(df, lat_col, lon_col, assignments):
    vehicle_routes = {vehicle: [] for vehicle in assignments.keys()}

    for vehicle, stt_values in assignments.items():
        for stt in stt_values:
            stop_data = df[df['id'] == stt]
            if not stop_data.empty:
                lat = stop_data.iloc[0][lat_col]
                lon = stop_data.iloc[0][lon_col]
                vehicle_routes[vehicle].append((lat, lon))
            else:
                print(f"Warning: STT value {stt} for {vehicle} not found in DataFrame.")
    return vehicle_routes


# Read Excel file and process data
df, lat_col, lon_col = load_and_process_data("RouteData.xlsx")

# Assign stops to vehicles
vehicle_routes = assign_stops_by_stt_values(df, lat_col, lon_col, default_vehicle_assignments)

# Display routes for confirmation
print("\n--- Vehicle Routes after Automated Assignment by STT values ---")
for vehicle, stops in vehicle_routes.items():
    print(f"{vehicle} has {len(stops)} stops:")
    for stop in stops:
        print(f"   {stop}")

# Display the head of the DataFrame for confirmation
print("\n--- DataFrame Head ---")
print(df.head())

import folium
import itertools

# Calculate the center of the map based on all stops
all_lats = [coord[0] for stops in vehicle_routes.values() for coord in stops]
all_lons = [coord[1] for stops in vehicle_routes.values() for coord in stops]

map_center_lat = sum(all_lats) / len(all_lats) if all_lats else df[lat_col].mean()
map_center_lon = sum(all_lons) / len(all_lons) if all_lons else df[lon_col].mean()

# Create a folium map
m = folium.Map(location=[map_center_lat, map_center_lon], zoom_start=12)

# Define a list of distinct colors for vehicles
colors = itertools.cycle([
    'red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred', 'beige',
    'darkblue', 'darkgreen', 'cadetblue', 'darkpurple', 'white', 'pink', 'lightblue',
    'lightgreen', 'gray', 'black', 'lightgray'
])

# Dictionary to store vehicle colors for the legend
vehicle_colors = {}

# Add markers for each vehicle's stops with different colors
for vehicle, stops in vehicle_routes.items():
    color = next(colors)
    vehicle_colors[vehicle] = color # Store color for legend
    for i, stop in enumerate(stops):
        folium.Marker(
            location=[stop[0], stop[1]],
            popup=f"Vehicle: {vehicle}<br>Stop {i+1}<br>Lat: {stop[0]:.4f}<br>Lon: {stop[1]:.4f}",
            icon=folium.Icon(color=color)
        ).add_to(m)

# Add a legend to the map
legend_html = '<div style="position: fixed; bottom: 50px; left: 50px; width: 120px; height: auto; z-index:9999; font-size:14px; background-color:white; border:2px solid grey; border-radius:5px; padding: 10px;"><b>Vehicles</b><br>'
for vehicle, color in vehicle_colors.items():
    legend_html += f'<i class="fa fa-map-marker fa-1x" style="color:{color}"></i> {vehicle}<br>'
legend_html += '</div>'
m.get_root().html.add_child(folium.Element(legend_html))

# Display the map
m

# PART 3: FINDING THE OPTIMAL ROUTE (TSP brute force)
import osmnx as ox
import itertools
from datetime import datetime, time, timedelta
import random

# Dictionary to cache graphs by network type to avoid re-downloading identical graphs
G_distance_optimized_cache = {}
G_time_optimized_cache = {}

def get_graph(network_type, point=None, dist=None, bbox=None):
    """
    Retrieves an OSMnx graph from cache or downloads it if not available.
    Caches the graph based on network type.
    """
    cache_key = network_type
    if point:
        cache_key += f"_{point[0]:.4f}_{point[1]:.4f}_{dist}"
    elif bbox:
        cache_key += f"_{bbox[0]:.4f}_{bbox[1]:.4f}_{bbox[2]:.4f}_{bbox[3]:.4f}"

    if cache_key in G_distance_optimized_cache:
        return G_distance_optimized_cache[cache_key]

    G = None
    if point and dist:
        G = ox.graph_from_point(point, dist=dist, network_type=network_type)
    elif bbox:
        north, south, east, west = bbox
        G = ox.graph_from_bbox(north, south, east, west, network_type=network_type)
    else:
        raise ValueError("Either point and dist or bbox must be provided.")

    # Add relevant attributes for routing
    G = ox.add_edge_speeds(G)
    G = ox.add_edge_travel_times(G) # Adds 'travel_time' attribute based on speed

    G_distance_optimized_cache[cache_key] = G
    return G

def get_traffic_multiplier(departure_time_str):
    dep_time = datetime.strptime(departure_time_str, '%H:%M').time()
    morning_rush_start = time(7, 0)
    morning_rush_end = time(9, 30)
    evening_rush_start = time(16, 30)
    evening_rush_end = time(19, 0)

    if (morning_rush_start <= dep_time <= morning_rush_end) or \
       (evening_rush_start <= dep_time <= evening_rush_end):
        return 1.5 # Simulate 50% increase in travel time during rush hours
    else:
        return 1.0

def calculate_optimal_distance_routes(vehicle_routes_data):
    """
    Calculates the optimal distance-based route for each vehicle using brute force TSP.
    """
    optimal_routes_per_vehicle = {}
    if not vehicle_routes_data:
        return optimal_routes_per_vehicle

    all_stops_coords = []
    for stops in vehicle_routes_data.values():
        all_stops_coords.extend(stops)

    if not all_stops_coords:
        return optimal_routes_per_vehicle

    # Calculate the overall center of all stops to get a graph covering the area
    map_center_lat = sum(p[0] for p in all_stops_coords) / len(all_stops_coords)
    map_center_lon = sum(p[1] for p in all_stops_coords) / len(all_stops_coords)
    # Get a graph for distance calculations. Use a larger dist to ensure connectivity.
    G_distance_optimized = get_graph('drive', point=(map_center_lat, map_center_lon), dist=5000)

    for vehicle, stops in vehicle_routes_data.items():
        if not stops:
            print(f"No stops assigned for {vehicle}. Skipping distance optimization.")
            optimal_routes_per_vehicle[vehicle] = {"min_distance": float('inf'), "best_route": None}
            continue

        min_distance_vehicle = float('inf')
        best_route_sequence_vehicle = None

        # Iterate through all possible permutations of stops for the current vehicle
        for perm in itertools.permutations(stops):
            current_permutation_total_distance_km = 0

            # Calculate the total distance for the current permutation using OSMnx road network
            for i in range(len(perm) - 1):
                orig_point = perm[i]
                dest_point = perm[i+1]

                # Find the nearest network nodes to the origin and destination points
                orig_node = ox.distance.nearest_nodes(G_distance_optimized, orig_point[1], orig_point[0])
                dest_node = ox.distance.nearest_nodes(G_distance_optimized, dest_point[1], dest_point[0])

                # Calculate the shortest path based on distance (length)
                route_segment = ox.shortest_path(G_distance_optimized, orig_node, dest_node, weight='length')

                if route_segment:
                    segment_distance_meters = 0
                    for u_edge, v_edge in zip(route_segment[:-1], route_segment[1:]):
                        edge_data = G_distance_optimized.get_edge_data(u_edge, v_edge, key=0)
                        if edge_data:
                            segment_distance_meters += edge_data.get('length', 0)
                    current_permutation_total_distance_km += segment_distance_meters / 1000  # Convert to km
                else:
                    current_permutation_total_distance_km = float('inf')
                    break # Break inner loop, this permutation is not viable

            # Update if a shorter distance route is found for the current vehicle
            if current_permutation_total_distance_km < min_distance_vehicle:
                min_distance_vehicle = current_permutation_total_distance_km
                best_route_sequence_vehicle = perm # Store the sequence of stops

        optimal_routes_per_vehicle[vehicle] = {
            "min_distance": min_distance_vehicle,
            "best_route": best_route_sequence_vehicle
        }

    return optimal_routes_per_vehicle

def calculate_optimal_time_routes(vehicle_routes_data):
    """
    Calculates the optimal time-based route for each vehicle using brute force TSP.
    Incorporates vehicle-specific departure times and traffic multipliers.
    Caches the time-optimized graph.
    """
    optimal_time_routes_per_vehicle = {}
    if not vehicle_routes_data:
        return optimal_time_routes_per_vehicle

    all_stops_coords = []
    for stops in vehicle_routes_data.values():
        all_stops_coords.extend(stops)

    if not all_stops_coords:
        return optimal_time_routes_per_vehicle

    map_center_lat = sum(p[0] for p in all_stops_coords) / len(all_stops_coords)
    map_center_lon = sum(p[1] for p in all_stops_coords) / len(all_stops_coords)

    # Get a graph for time calculations. This will be cached in G_time_optimized_cache
    G_time_optimized = get_graph('drive', point=(map_center_lat, map_center_lon), dist=5000)
    globals()['G_time_optimized_cache'] = G_time_optimized # Make it globally accessible for other parts

    for vehicle, stops in vehicle_routes_data.items():
        if not stops:
            print(f"No stops assigned for {vehicle}. Skipping time optimization.")
            optimal_time_routes_per_vehicle[vehicle] = {"min_time_seconds": float('inf'), "best_time_route_sequence": None}
            continue

        min_time_vehicle = float('inf')
        best_time_route_sequence_vehicle = None

        params = get_vehicle_params(vehicle)
        vehicle_departure_time = params.get('departure_time', '09:00')
        initial_traffic_multiplier = get_traffic_multiplier(vehicle_departure_time)

        # Define custom weight function for shortest path that incorporates the initial traffic
        def get_edge_travel_time_with_initial_traffic(u, v, data):
            return data.get('travel_time', float('inf')) * initial_traffic_multiplier

        # Iterate through all possible permutations of stops for the current vehicle
        for perm in itertools.permutations(stops):
            current_permutation_total_time_sec = 0

            # Calculate the total time for the current permutation using OSMnx road network
            for i in range(len(perm) - 1):
                orig_point = perm[i]
                dest_point = perm[i+1]

                # Find the nearest network nodes to the origin and destination points
                orig_node = ox.distance.nearest_nodes(G_time_optimized, orig_point[1], orig_point[0])
                dest_node = ox.distance.nearest_nodes(G_time_optimized, dest_point[1], dest_point[0])

                # Calculate the shortest path based on travel time with initial traffic
                route_segment = ox.shortest_path(G_time_optimized, orig_node, dest_node, weight=get_edge_travel_time_with_initial_traffic)

                if route_segment:
                    segment_travel_time_sec = 0
                    for u_edge, v_edge in zip(route_segment[:-1], route_segment[1:]):
                        edge_data = G_time_optimized.get_edge_data(u_edge, v_edge, key=0)
                        if edge_data:
                            segment_travel_time_sec += edge_data.get('travel_time', 0) * initial_traffic_multiplier
                    current_permutation_total_time_sec += segment_travel_time_sec
                else:
                    current_permutation_total_time_sec = float('inf')
                    break # Break inner loop, this permutation is not viable

            # Update if a shorter time route is found for the current vehicle
            if current_permutation_total_time_sec < min_time_vehicle:
                min_time_vehicle = current_permutation_total_time_sec
                best_time_route_sequence_vehicle = perm # Store the sequence of stops

        optimal_time_routes_per_vehicle[vehicle] = {
            "min_time_seconds": min_time_vehicle,
            "best_time_route_sequence": best_time_route_sequence_vehicle
        }

    return optimal_time_routes_per_vehicle

# Helper function to simulate external real-time traffic updates
def get_simulated_real_time_traffic_multiplier(current_simulated_time):
    current_hour = current_simulated_time.hour
    current_minute = current_simulated_time.minute
    # Example: Higher traffic during morning/evening rush hours, random spikes
    if 7 <= current_hour < 9 or (current_hour == 9 and current_minute <= 30): # Morning rush
        if random.random() < 0.7: # 70% chance of heavy traffic
            return random.uniform(1.5, 2.0)
        else: # 30% chance of moderate traffic
            return random.uniform(1.0, 1.2)
    elif 16 <= current_hour < 19 or (current_hour == 19 and current_minute <= 0): # Evening rush
        if random.random() < 0.7:
            return random.uniform(1.5, 2.0)
        else: # 30% chance of moderate traffic
            return random.uniform(1.0, 1.2)
    elif random.random() < 0.1: # 10% chance of a random traffic spike any other time
        return random.uniform(1.3, 1.7)
    else: # Normal traffic
        return 1.0


# --- PART 3: FINDING THE OPTIMAL ROUTE (TSP brute force using OSMnx Road Network Distances and Times) ---

# Calculate optimal distance-based routes
print("\n### Calculating Distance-Optimized Routes ###")
optimal_routes_per_vehicle = calculate_optimal_distance_routes(vehicle_routes)

print("\n--- Optimal Routes per Vehicle (OSMnx Distance-Optimized) ---")
if optimal_routes_per_vehicle:
    for vehicle, data in optimal_routes_per_vehicle.items():
        print(f"\n{vehicle}:")
        if data["min_distance"] == float('inf'):
            print(f"  No valid route found.")
        else:
            print(f"  Optimal route distance: {data['min_distance']:.2f} km")
            print(f"  Best route: {data['best_route']}")
else:
    print("Skipping distance-optimized route calculation as vehicle_routes is empty.")

# Calculate optimal time-based routes (This will also build G_time_optimized and cache it)
print("\n### Calculating Time-Optimized Routes (with initial traffic) ###")
optimal_time_routes_per_vehicle = calculate_optimal_time_routes(vehicle_routes)

print("\n--- Initial Time-Optimized Routes Calculated (before dynamic simulation) ---")
if optimal_time_routes_per_vehicle:
    for vehicle, data in optimal_time_routes_per_vehicle.items():
        print(f"  {vehicle}: Optimal time: {data['min_time_seconds'] / 60:.2f} minutes")
else:
    print("Skipping time-optimized route calculation as vehicle_routes is empty.")

# PART 4: CREATE REALISTIC MAPS
import folium
import osmnx as ox
import itertools
from datetime import datetime, time

# --- Map 1: Distance-Optimized Routes ---
print("### Visualizing Distance-Optimized Routes ###")

# Calculate the overall center of all optimal routes for map centering
all_optimal_stops_dist = []
for vehicle, data in optimal_routes_per_vehicle.items():
    if data["best_route"]:
        all_optimal_stops_dist.extend(data["best_route"])

if all_optimal_stops_dist:
    map_center_lat_dist = sum(p[0] for p in all_optimal_stops_dist) / len(all_optimal_stops_dist)
    map_center_lon_dist = sum(p[1] for p in all_optimal_stops_dist) / len(all_optimal_stops_dist)
else:
    # Fallback if no optimal routes were found or assigned
    if 'df' in globals() and not df.empty and 'lat_col' in globals() and 'lon_col' in globals():
        map_center_lat_dist = df[lat_col].mean()
        map_center_lon_dist = df[lon_col].mean()
    else:
        map_center_lat_dist = 0 # Default if no data is available
        map_center_lon_dist = 0 # Default if no data is available
        print("Warning: No optimal routes or DataFrame available to center the distance-optimized map. Using default (0,0).")

# Create map centered on the overall optimal routes
m_dist = folium.Map(location=[map_center_lat_dist, map_center_lon_dist], zoom_start=12)

# Define a list of distinct colors for vehicle routes
colors_dist = itertools.cycle([
    'red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred', 'beige',
    'darkblue', 'darkgreen', 'cadetblue', 'darkpurple', 'white', 'pink', 'lightblue',
    'lightgreen', 'gray', 'black', 'lightgray'
])
vehicle_route_colors_dist = {}

# Check if G_distance_optimized_cache is available from PART 3
if 'G_distance_optimized_cache' in globals() and 'drive' in G_distance_optimized_cache:
    G_map_dist = G_distance_optimized_cache['drive'] # Assuming 'drive' is the most common network type for distance
else:
    G_map_dist = None
    if all_optimal_stops_dist:
        print("Warning: G_distance_optimized_cache not found. Creating a new graph for distance map visualization.")
        # Get bounds of all optimal stops to create a new graph
        min_lat = min(s[0] for s in all_optimal_stops_dist)
        max_lat = max(s[0] for s in all_optimal_stops_dist)
        min_lon = min(s[1] for s in all_optimal_stops_dist)
        max_lon = max(s[1] for s in all_optimal_stops_dist)
        bbox = (max_lat, min_lon, min_lat, max_lon)
        north, south, east, west = bbox
        margin = 0.01 # degrees
        G_map_dist = ox.graph_from_bbox(north + margin, south - margin, east + margin, west - margin, network_type='drive')

if G_map_dist:
    for vehicle, data in optimal_routes_per_vehicle.items():
        best_route = data["best_route"]
        if not best_route:
            print(f"No optimal distance-optimized route for {vehicle}. Skipping map drawing.")
            continue

        route_color = next(colors_dist)
        vehicle_route_colors_dist[vehicle] = route_color

        # Draw routes for each segment of the optimal path
        for i in range(len(best_route) - 1):
            orig_point = best_route[i]
            dest_point = best_route[i+1]

            # Find the nearest network nodes to the origin and destination points
            orig_node = ox.distance.nearest_nodes(G_map_dist, orig_point[1], orig_point[0])
            dest_node = ox.distance.nearest_nodes(G_map_dist, dest_point[1], dest_point[0])

            # Calculate the shortest path between these nodes
            route = ox.shortest_path(G_map_dist, orig_node, dest_node, weight='length') # Using length for visualization

            if route:
                # Get the coordinates for the path
                route_coords = [(G_map_dist.nodes[n]['y'], G_map_dist.nodes[n]['x']) for n in route]
                # Add the path to the map
                folium.PolyLine(route_coords, color=route_color, weight=4, opacity=0.8,
                                popup=f"{vehicle} Dist-Opt Segment {i+1}").add_to(m_dist)
            else:
                print(f"Could not find distance-optimized route segment for {vehicle} between {orig_point} and {dest_point}.")

    # Add a legend for the routes
    legend_html_dist = '<div style="position: fixed; bottom: 50px; left: 50px; width: 150px; height: auto; z-index:9999; font-size:14px; background-color:white; border:2px solid grey; border-radius:5px; padding: 10px;"><b>Distance-Opt Routes</b><br>'
    for vehicle, color in vehicle_route_colors_dist.items():
        legend_html_dist += f'<i class="fa fa-map-marker fa-1x" style="color:{color}"></i> {vehicle}<br>'
    legend_html_dist += '</div>'
    m_dist.get_root().html.add_child(folium.Element(legend_html_dist))

    # Display the distance-optimized map
    display(m_dist)
else:
    print("Cannot display distance-optimized map as graph was not successfully generated.")


# --- Map 2: Time-Optimized Routes (with simulated traffic) ---
print("\n### Visualizing Time-Optimized Routes (with simulated traffic) ###")

# Create the time-optimized graph here, as it is used for visualization and Part 5 simulation
# We need a graph G to perform shortest path calculations.
# Re-create a graph if not already available from previous parts, centered on all stops.
all_stops_coords = []
G_time_optimized = None # Initialize G_time_optimized to None

if 'vehicle_routes' in globals() and vehicle_routes:
    for stops in vehicle_routes.values():
        all_stops_coords.extend(stops)

    if all_stops_coords:
        map_center_lat = sum(p[0] for p in all_stops_coords) / len(all_stops_coords)
        map_center_lon = sum(p[1] for p in all_stops_coords) / len(all_stops_coords)

        # Assuming 'drive' network type for generality in this simulation.
        G_time_optimized = ox.graph_from_point(
            (map_center_lat, map_center_lon),
            dist=2000, # A reasonable distance to cover nearby roads for a local delivery scenario
            network_type='drive'
        )
        G_time_optimized = ox.add_edge_speeds(G_time_optimized)
        G_time_optimized = ox.add_edge_travel_times(G_time_optimized) # Adds 'travel_time' attribute based on speed
        print("\nRoad network graph (OSMnx) created for dynamic re-routing simulation.")
    else:
        print("\nNo stops defined to create an OSMnx graph for dynamic re-routing simulation.")
        # G_time_optimized remains None
else:
    print("\nWarning: vehicle_routes not found or is empty. Cannot create OSMnx graph for dynamic re-routing simulation.")
    # G_time_optimized remains None

# Helper function for static traffic multiplier (used for initial time-optimized route calculation and insights)
def get_traffic_multiplier(departure_time_str):
    dep_time = datetime.strptime(departure_time_str, '%H:%M').time()
    morning_rush_start = time(7, 0)
    morning_rush_end = time(9, 30)
    evening_rush_start = time(16, 30)
    evening_rush_end = time(19, 0)

    if (morning_rush_start <= dep_time <= morning_rush_end) or \
       (evening_rush_start <= dep_time <= evening_rush_end):
        return 1.5 # Simulate 50% increase in travel time during rush hours
    else:
        return 1.0

# --- Time-Optimized Route Calculation (TSP brute force using OSMnx Road Network Travel Times) ---
optimal_time_routes_per_vehicle = {}

if 'G_time_optimized' in globals() and G_time_optimized and \
   'vehicle_routes' in globals() and vehicle_routes:

    for vehicle, stops in vehicle_routes.items():
        if not stops:
            print(f"No stops assigned for {vehicle}. Skipping time-optimized route optimization.")
            continue

        min_time_vehicle = float('inf')
        best_time_route_sequence_vehicle = None

        params = get_vehicle_params(vehicle)
        vehicle_departure_time = params.get('departure_time', '09:00')
        initial_traffic_multiplier = get_traffic_multiplier(vehicle_departure_time)

        # Define custom weight function for shortest path that incorporates the initial traffic
        def get_edge_travel_time_with_initial_traffic(u, v, data):
            return data.get('travel_time', float('inf')) * initial_traffic_multiplier

        # Iterate through all possible permutations of stops for the current vehicle
        for perm in itertools.permutations(stops):
            current_permutation_total_time_sec = 0

            # Calculate the total time for the current permutation using OSMnx road network
            for i in range(len(perm) - 1):
                orig_point = perm[i]
                dest_point = perm[i+1]

                # Find the nearest network nodes to the origin and destination points
                orig_node = ox.distance.nearest_nodes(G_time_optimized, orig_point[1], orig_point[0])
                dest_node = ox.distance.nearest_nodes(G_time_optimized, dest_point[1], dest_point[0])

                # Calculate the shortest path based on travel time with initial traffic
                route_segment = ox.shortest_path(G_time_optimized, orig_node, dest_node, weight=get_edge_travel_time_with_initial_traffic)

                if route_segment:
                    segment_travel_time_sec = 0
                    for u_edge, v_edge in zip(route_segment[:-1], route_segment[1:]):
                        edge_data = G_time_optimized.get_edge_data(u_edge, v_edge, key=0)
                        if edge_data:
                            segment_travel_time_sec += edge_data.get('travel_time', 0) * initial_traffic_multiplier
                    current_permutation_total_time_sec += segment_travel_time_sec
                else:
                    current_permutation_total_time_sec = float('inf')
                    break # Break inner loop, this permutation is not viable

            # Update if a shorter time route is found for the current vehicle
            if current_permutation_total_time_sec < min_time_vehicle:
                min_time_vehicle = current_permutation_total_time_sec
                best_time_route_sequence_vehicle = perm # Store the sequence of stops

        optimal_time_routes_per_vehicle[vehicle] = {
            "min_time_seconds": min_time_vehicle,
            "best_time_route_sequence": best_time_route_sequence_vehicle
        }
    print("--- Initial Time-Optimized Routes Calculated (before dynamic simulation) ---")
    for vehicle, data in optimal_time_routes_per_vehicle.items():
        print(f"  {vehicle}: Optimal time: {data['min_time_seconds'] / 60:.2f} minutes")
else:
    print("Skipping time-optimized route calculation as G_time_optimized or vehicle_routes is not available.")


# Now that optimal_time_routes_per_vehicle is calculated, proceed with visualization
if 'G_time_optimized' in globals() and G_time_optimized and \
   'optimal_time_routes_per_vehicle' in globals() and optimal_time_routes_per_vehicle:

    all_optimal_stops_time = []
    for vehicle, data in optimal_time_routes_per_vehicle.items():
        if data["best_time_route_sequence"]:
            all_optimal_stops_time.extend(data["best_time_route_sequence"])

    if all_optimal_stops_time:
        map_center_lat_time = sum(p[0] for p in all_optimal_stops_time) / len(all_optimal_stops_time)
        map_center_lon_time = sum(p[1] for p in all_optimal_stops_time) / len(all_optimal_stops_time)
    else:
        map_center_lat_time = map_center_lat_dist # Fallback to distance map center
        map_center_lon_time = map_center_lon_dist
        print("Warning: No optimal time-optimized routes to center the map. Using distance-optimized map center.")

    m_time = folium.Map(location=[map_center_lat_time, map_center_lon_time], zoom_start=12)

    colors_time = itertools.cycle([
        'darkblue', 'darkgreen', 'purple', 'orange', 'cadetblue', 'red', 'lightred', 'beige',
        'darkred', 'lightred', 'beige', 'white', 'pink', 'lightblue',
        'lightgreen', 'gray', 'black', 'lightgray'
    ])
    vehicle_route_colors_time = {}

    for vehicle, data in optimal_time_routes_per_vehicle.items():
        best_time_route_sequence = data["best_time_route_sequence"]
        if not best_time_route_sequence:
            print(f"No optimal time-optimized route for {vehicle}. Skipping map drawing.")
            continue

        route_color_time = next(colors_time)
        vehicle_route_colors_time[vehicle] = route_color_time

        # Get vehicle parameters for departure time
        params = get_vehicle_params(vehicle)
        vehicle_departure_time = params.get('departure_time', '09:00')
        traffic_multiplier = get_traffic_multiplier(vehicle_departure_time)

        # Define custom weight function for shortest path that incorporates traffic
        def get_edge_travel_time_with_traffic_for_map(u, v, data):
            return data.get('travel_time', float('inf')) * traffic_multiplier

        for i in range(len(best_time_route_sequence) - 1):
            orig_point = best_time_route_sequence[i]
            dest_point = best_time_route_sequence[i+1]

            orig_node = ox.distance.nearest_nodes(G_time_optimized, orig_point[1], orig_point[0])
            dest_node = ox.distance.nearest_nodes(G_time_optimized, dest_point[1], dest_point[0])

            # Use the time-optimized graph and weight for route calculation
            route = ox.shortest_path(G_time_optimized, orig_node, dest_node, weight=get_edge_travel_time_with_traffic_for_map)

            if route:
                route_coords = [(G_time_optimized.nodes[n]['y'], G_time_optimized.nodes[n]['x']) for n in route]
                folium.PolyLine(route_coords, color=route_color_time, weight=4, opacity=0.8,
                                popup=f"{vehicle} Time-Opt Segment {i+1} (Traffic: {traffic_multiplier:.1f}x)").add_to(m_time)
            else:
                print(f"Could not find time-optimized route segment for {vehicle} between {orig_point} and {dest_point}.")

    legend_html_time = '<div style="position: fixed; bottom: 50px; left: 50px; width: 150px; height: auto; z-index:9999; font-size:14px; background-color:white; border:2px solid grey; border-radius:5px; padding: 10px;"><b>Time-Opt Routes</b><br>'
    for vehicle, color in vehicle_route_colors_time.items():
        legend_html_time += f'<i class="fa fa-map-marker fa-1x" style="color:{color}"></i> {vehicle}<br>'
    legend_html_time += '</div>'
    m_time.get_root().html.add_child(folium.Element(legend_html_time))

    # Display the time-optimized map
    display(m_time)

# PART 5: CALCULATING INSIGHTS
import osmnx as ox
import pandas as pd
import itertools
import random
from datetime import datetime, time, timedelta # Import for dynamic traffic simulation

# --- Helper function for dynamic traffic multiplier ---
def get_traffic_multiplier_dynamic(departure_time_str, current_simulated_time=None):
    if current_simulated_time is None:
        # Fallback to initial departure time if current_simulated_time is not provided
        dep_time = datetime.strptime(departure_time_str, '%H:%M').time()
    else:
        dep_time = current_simulated_time.time()

    morning_rush_start = time(7, 0)
    morning_rush_end = time(9, 30)
    evening_rush_start = time(16, 30)
    evening_rush_end = time(19, 0)

    if (morning_rush_start <= dep_time <= morning_rush_end) or \
       (evening_rush_start <= dep_time <= evening_rush_end):
        return 1.5
    else:
        return 1.0

print("### PART 5: Calculating Insights ###")

# Check if optimal_routes_per_vehicle is defined from PART 3
if 'optimal_routes_per_vehicle' not in globals() or not optimal_routes_per_vehicle:
    print("Warning: optimal_routes_per_vehicle not found or is empty. Please ensure PART 3 has been run before this cell.")
    insights_df = pd.DataFrame() # Create an empty DataFrame to avoid errors later
else:
    # Initialize lists to store insights for each vehicle
    vehicle_insights = []

    for vehicle, data in optimal_routes_per_vehicle.items():
        min_d_vehicle = data['min_distance']

        # Get vehicle-specific parameters using the helper function (defined in Part 2)
        params = get_vehicle_params(vehicle)
        vehicle_l_per_100km = params["L_PER_100KM"]
        vehicle_avg_speed_kmh = params["AVG_SPEED_KMH"]
        vehicle_departure_time = params.get('departure_time', '09:00')

        # Calculate traffic multiplier based on departure time using the new helper (defined in Part 4)
        # Note: get_traffic_multiplier for insights uses the static one defined in Part 4
        traffic_multiplier = get_traffic_multiplier(vehicle_departure_time)

        # Calculate insights for the current vehicle, applying traffic multiplier to time
        fuel_consumption = (min_d_vehicle * vehicle_l_per_100km) / 100  # L
        fuel_cost = fuel_consumption * COST_PER_LITER  # VND
        time_hours = (min_d_vehicle / vehicle_avg_speed_kmh) * traffic_multiplier  # hours, with traffic
        time_minutes = time_hours * 60 # minutes

        vehicle_insights.append({
            "Vehicle": vehicle,
            "Optimal Distance (km)": min_d_vehicle,
            "Fuel (L)": fuel_consumption,
            "Cost (VND)": fuel_cost,
            "Time (hours)": time_hours,
            "Time (minutes)": time_minutes
        })

    # Convert to DataFrame for easier display and plotting
    insights_df = pd.DataFrame(vehicle_insights)

    # --- Add Expected Value Calculations for Comparison ---
    insights_df['Fuel Efficiency (km/L)'] = insights_df['Optimal Distance (km)'] / insights_df['Fuel (L)']
    insights_df['Cost per km (VND/km)'] = insights_df['Cost (VND)'] / insights_df['Optimal Distance (km)']
    insights_df['Average Speed (km/h)'] = insights_df['Optimal Distance (km)'] / insights_df['Time (hours)']

    print("--- Vehicle Performance Insights ---")
    print(insights_df.round(2).to_string(index=False))


# --- Dynamic Re-routing Simulation Section ---
# This section simulates dynamic re-routing based on real-time traffic updates.

# G_time_optimized and optimal_time_routes_per_vehicle are now expected to be created in Part 4

if 'G_time_optimized' in globals() and G_time_optimized:
    # Helper function to simulate external real-time traffic updates
    def get_simulated_real_time_traffic_multiplier(current_simulated_time):
        current_hour = current_simulated_time.hour
        current_minute = current_simulated_time.minute
        # Example: Higher traffic during morning/evening rush hours, random spikes
        if 7 <= current_hour < 9 or (current_hour == 9 and current_minute <= 30): # Morning rush
            if random.random() < 0.7: # 70% chance of heavy traffic
                return random.uniform(1.5, 2.0)
            else: # 30% chance of moderate traffic
                return random.uniform(1.0, 1.2)
        elif 16 <= current_hour < 19 or (current_hour == 19 and current_minute <= 0): # Evening rush
            if random.random() < 0.7:
                return random.uniform(1.5, 2.0)
            else: # 30% chance of moderate traffic
                return random.uniform(1.0, 1.2)
        elif random.random() < 0.1: # 10% chance of a random traffic spike any other time
            return random.uniform(1.3, 1.7)
        else: # Normal traffic
            return 1.0

    def simulate_dynamic_re_routing(vehicle_name, initial_stops, G_graph, total_sim_duration_minutes=60, check_interval_minutes=10):
        print(f"\n--- Starting dynamic simulation for {vehicle_name} ---")

        current_stops_sequence = list(initial_stops)
        params = get_vehicle_params(vehicle_name)
        initial_departure_time_str = params.get('departure_time', '09:00')

        # Start simulation at the vehicle's departure time on a arbitrary day (e.g., Jan 1, 2023)
        current_simulated_time = datetime.strptime(initial_departure_time_str, '%H:%M').replace(year=2023, month=1, day=1)

        completed_segments = []
        current_location = current_stops_sequence[0] # Assume first stop is the starting point
        remaining_stops = current_stops_sequence[1:] # All other stops are destinations

        total_journey_time_taken_sec = 0
        total_journey_distance_km = 0

        print(f"Initial route calculation for {vehicle_name} at simulated time {current_simulated_time.strftime('%H:%M')}")
        # Get initial traffic multiplier based on the vehicle's scheduled departure time
        traffic_multiplier_initial = get_traffic_multiplier_dynamic(initial_departure_time_str, current_simulated_time)

        def calculate_current_optimal_path(start_point, end_points, G, current_sim_time, initial_dep_time_str):
            """
            Calculates the optimal path from start_point to the next stop in end_points
            considering dynamic traffic conditions.
            """
            if not end_points:
                return None, 0, 0 # No more destinations

            next_dest_point = end_points[0] # Only calculate to the very next stop

            # Get the current dynamic traffic multiplier
            current_traffic_mult = get_simulated_real_time_traffic_multiplier(current_sim_time) # Use real-time simulation

            # Define a custom weight function for shortest path that incorporates dynamic traffic
            def get_edge_travel_time_with_dynamic_traffic(u, v, data):
                return data.get('travel_time', float('inf')) * current_traffic_mult

            # Find the nearest network nodes to the origin and destination points
            orig_node = ox.distance.nearest_nodes(G, start_point[1], start_point[0])
            dest_node = ox.distance.nearest_nodes(G, next_dest_point[1], dest_point[0])

            # Calculate the shortest path between these nodes based on dynamically adjusted travel time
            route = ox.shortest_path(G, orig_node, dest_node, weight=get_edge_travel_time_with_dynamic_traffic)

            if route:
                segment_travel_time = 0
                segment_distance = 0
                for u_edge, v_edge in zip(route[:-1], route[1:]):
                    edge_data = G.get_edge_data(u_edge, v_edge, key=0)
                    if edge_data:
                        segment_travel_time += edge_data.get('travel_time', 0) * current_traffic_mult
                        segment_distance += edge_data.get('length', 0)
                return route, segment_travel_time, segment_distance / 1000 # Return time in seconds, distance in km
            return None, float('inf'), float('inf') # No path found


        # Main simulation loop
        while remaining_stops and total_journey_time_taken_sec < total_sim_duration_minutes * 60:
            # Re-evaluate route at defined intervals or at the beginning of the journey
            if total_journey_time_taken_sec % (check_interval_minutes * 60) == 0 or total_journey_time_taken_sec == 0:
                print(f"\n-- Re-evaluating route for {vehicle_name} at simulated time {current_simulated_time.strftime('%H:%M')} --")
                current_route_segment, estimated_segment_time, estimated_segment_distance = \
                    calculate_current_optimal_path(current_location, remaining_stops, G_graph, current_simulated_time, initial_departure_time_str)

                if current_route_segment is None:
                    print(f"No path found from {current_location} to next stop {remaining_stops[0]}. Ending simulation.")
                    break

                print(f"  New estimated time to next stop: {estimated_segment_time:.2f} sec, distance: {estimated_segment_distance:.2f} km")
                print(f"  Traffic multiplier (based on {current_simulated_time.strftime('%H:%M')}): {get_simulated_real_time_traffic_multiplier(current_simulated_time):.1f}x") # Display current traffic multiplier

            # Simulate passage of time in increments of check_interval_minutes
            # Assume vehicle travels for 'check_interval_minutes' or until it reaches the next stop
            travel_time_this_interval_sec = min(estimated_segment_time, check_interval_minutes * 60)

            total_journey_time_taken_sec += travel_time_this_interval_sec
            current_simulated_time += timedelta(seconds=travel_time_this_interval_sec)

            # If the vehicle reached the destination within this interval
            if travel_time_this_interval_sec == estimated_segment_time:
                completed_segments.append((current_location, remaining_stops[0]))
                total_journey_distance_km += estimated_segment_distance
                current_location = remaining_stops.pop(0) # Move to the next stop
                print(f"  {vehicle_name} arrived at stop. Total time: {total_journey_time_taken_sec/60:.2f} min. Current simulated time: {current_simulated_time.strftime('%H:%M')}")
                if not remaining_stops:
                    print(f"  {vehicle_name} completed all stops!")
                    break # All stops visited
            else:
                # If destination not reached, continue simulation in next interval
                pass


        print(f"\n--- Simulation for {vehicle_name} finished ---")
        print(f"Total simulated travel time: {total_journey_time_taken_sec / 60:.2f} minutes")
        print(f"Total simulated distance: {total_journey_distance_km:.2f} km")
        if remaining_stops: # If there are still stops left
          print(f"Remaining stops: {len(remaining_stops)}")

        return {
            "Vehicle": vehicle_name,
            "Simulated Travel Time (minutes)": total_journey_time_taken_sec / 60,
            "Simulated Distance (km)": total_journey_distance_km,
            "Stops Completed": len(completed_segments),
            "All Stops Reached": not bool(remaining_stops)
        }

    # Run dynamic re-routing simulation for all vehicles and collect results
    simulation_results = []
    for vehicle_name, initial_stops in vehicle_routes.items():
        if initial_stops:
            result = simulate_dynamic_re_routing(
                vehicle_name,
                initial_stops,
                G_time_optimized,
                total_sim_duration_minutes=90, # Simulate for 90 minutes
                check_interval_minutes=15 # Re-check traffic and re-route every 15 minutes
            )
            simulation_results.append(result)
        else:
            print(f"No stops for {vehicle_name}. Skipping dynamic re-routing simulation.")

    # Display simulation results in a DataFrame
    if simulation_results:
        dynamic_simulation_df = pd.DataFrame(simulation_results)
        print("\n--- Dynamic Re-routing Simulation Results ---")
        print(dynamic_simulation_df.round(2).to_string(index=False))
    else:
        print("No dynamic simulation results to display.")

else:
    print("Cannot proceed with dynamic re-routing simulation as the OSMnx graph (G_time_optimized) was not successfully generated.")

# PART 6: EXPORTING REPORT
output_file_name = 'Route_Optimization_Report.xlsx'

with pd.ExcelWriter(output_file_name) as writer:
    if 'insights_df' in globals() and not insights_df.empty:
        insights_df.to_excel(writer, sheet_name='Vehicle_Insights', index=False)
        print(f"'Vehicle_Insights' sheet written to {output_file_name}")
    else:
        print("Warning: insights_df is not available or empty. Skipping 'Vehicle_Insights' sheet.")

    if 'dynamic_simulation_df' in globals() and not dynamic_simulation_df.empty:
        dynamic_simulation_df.to_excel(writer, sheet_name='Dynamic_Simulation', index=False)
        print(f"'Dynamic_Simulation' sheet written to {output_file_name}")
    else:
        print("Warning: dynamic_simulation_df is not available or empty. Skipping 'Dynamic_Simulation' sheet.")

print(f"\nReport exported successfully to {output_file_name}")